Numpy   https://github.com/sakshigupta1528/Day2_Notebooks

In [ ]:

# ==============================================================================
# SECTION 1: WHY NUMPY EXISTS & THE SPEED GAP
# ==============================================================================
# In standard Python:
#   A list is an array of POINTERS to boxed objects scattered across heap memory.
# In NumPy:
#   An ndarray is a CONTIGUOUS block of raw, uniform primitive C-types in memory.
#   This enables CPU cache locality, SIMD vectorisation, and parallel processing.

import numpy as np

print(f"NumPy Version: {np.__version__}")

# Benchmark: Python loop vs. Vectorised NumPy operation (1,000,000 elements)
size = 1_000_000
py_list = list(range(size))
np_arr = np.arange(size)
print(np_arr)

NumPy Version: 2.1.3
[     0      1      2 ... 999997 999998 999999]


In [ ]:
# ==============================================================================
# SECTION 2: ARRAY CREATION & ATTRIBUTES
# ==============================================================================
# Seed for reproducibility
np.random.seed(42)

# 1. Creation from lists
a1 = np.array([1, 2, 3, 4], dtype=np.float32)

# 2. Structural initialisations
zeros = np.zeros((2, 3))               # 2x3 matrix of 0.0
ones = np.ones((2, 2), dtype=int)      # 2x2 matrix of 1s
full = np.full((2, 3), fill_value=7)   # 2x3 matrix filled with 7
identity = np.eye(3)                   # 3x3 Identity matrix

# 3. Range-based creation
seq_step = np.arange(0, 10, 2)         # start, stop (exclusive), step -> [0, 2, 4, 6, 8]
seq_lin = np.linspace(0, 1, 5)         # start, stop (inclusive), num points -> [0., 0.25, 0.5, 0.75, 1.]

# 4. Random arrays
rand_uniform = np.random.rand(2, 3)    # Uniform [0, 1)
rand_normal = np.random.randn(2, 3)    # Standard normal (mean 0, std 1)
rand_int = np.random.randint(1, 10, size=(2, 3)) # Discrete integers [low, high)

print("Array:\n", rand_int)
print("Attributes:")
print(f" - shape (dimensions):        {rand_int.shape}")
print(f" - ndim  (num of axes):       {rand_int.ndim}")
print(f" - size  (total elements):    {rand_int.size}")
print(f" - dtype (element data type): {rand_int.dtype}")

Array:
 [[6 9 1]
 [3 7 4]]
Attributes:
 - shape (dimensions):        (2, 3)
 - ndim  (num of axes):       2
 - size  (total elements):    6
 - dtype (element data type): int64


In [ ]:

# ==============================================================================
# SECTION 3: INDEXING, SLICING, & THE "VIEW VS COPY" GOTCHA
# ==============================================================================
mat = np.arange(1, 13).reshape(3, 4)
print("Original Matrix:\n", mat)

# Basic 2D Slicing: [rows, cols]
sub_mat = mat[0:2, 1:3]
print("\nSlice [0:2, 1:3]:\n", sub_mat)

# --- CRITICAL GOTCHA: Slices create VIEWS (shared memory), NOT deep copies! ---
sub_mat[0, 0] = 999
print("\nAfter modifying sub_mat[0, 0] to 999:")
print("Original Matrix is mutated!:\n", mat)

# To prevent mutating the original, explicitly use .copy()
mat_copy = mat[0:2, 1:3].copy()
mat_copy[0, 0] = -1
print("\nModifying an explicit copy does NOT mutate original:")
print(mat_copy)
print("Original mat[0, 1] remains:", mat[0, 1])

Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Slice [0:2, 1:3]:
 [[2 3]
 [6 7]]

After modifying sub_mat[0, 0] to 999:
Original Matrix is mutated!:
 [[  1 999   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Modifying an explicit copy does NOT mutate original:
[[-1  3]
 [ 6  7]]
Original mat[0, 1] remains: 999


In [ ]:

# ==============================================================================
# SECTION 4: BOOLEAN MASKING & FANCY INDEXING
# ==============================================================================
arr = np.array([10, 25, 30, 45, 50, 65])

# 1. Boolean Masking (filtering)
mask = arr > 30
print("Boolean Mask (arr > 30):", mask)
print("Filtered Elements:       ", arr[mask])

# In-place condition replacement
arr[arr > 40] = 0
print("After replacing values > 40 with 0:", arr)

# 2. Fancy Indexing (integer array indexing - always returns a COPY)
data = np.arange(10, 100, 10).reshape(3, 3)
print("\nData:\n", data)
rows = np.array([0, 2])
cols = np.array([1, 2])
print("Selected elements (0,1) and (1,2):", data[rows, cols])

Boolean Mask (arr > 30): [False False False  True  True  True]
Filtered Elements:        [45 50 65]
After replacing values > 40 with 0: [10 25 30  0  0  0]

Data:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Selected elements (0,1) and (2,2): [20 90]


In [ ]:
# ==============================================================================
# SECTION 5: SHAPE MANIPULATION & EXPANSIONS
# ==============================================================================
arr = np.arange(6) # [0, 1, 2, 3, 4, 5]

# 1. Reshape
r_arr = arr.reshape(2, 3)
print("Reshaped (2, 3):\n", r_arr)

# 2. Ravel (View where possible) vs Flatten (Always creates a Copy)
rav = r_arr.ravel()
print(rav)
flat = r_arr.flatten()
print(flat)

# 3. Transpose
print("Transposed (3, 2):\n", r_arr.T)

# 4. Dimension Expansion (used frequently in deep learning and broadcasting)
v = np.array([1, 2, 3]) # shape: (3,)
v_col1 = np.expand_dims(v, axis=1) # shape: (3, 1)
v_col2 = v[:, np.newaxis]          # shape: (3, 1)
print(v_col1)
print(v_col2)
print("Vector expanded to column shape:", v_col1.shape)

Reshaped (2, 3):
 [[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
Transposed (3, 2):
 [[0 3]
 [1 4]
 [2 5]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
Vector expanded to column shape: (3, 1)


In [ ]:
# ==============================================================================
# SECTION 7: AGGREGATIONS & THE AXIS PARAMETER
# ==============================================================================
# Visual rule for 2D:
# axis=0: Collapse rows (move down vertically -> compute for each column)
# axis=1: Collapse columns (move across horizontally -> compute for each row)

X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Data:\n", X)
print("Sum Total:           ", np.sum(X))
print("Sum axis=0 (per col):", np.sum(X, axis=0))
print("Sum axis=1 (per row):", np.sum(X, axis=1))
print("Mean per column:     ", np.mean(X, axis=0))
print("Std per row:         ", np.std(X, axis=1))
print("Index of max overall:", np.argmax(X))
print("Index of max per col:", np.argmax(X, axis=0))

Data:
 [[10 20 30]
 [40 50 60]]
Sum Total:            210
Sum axis=0 (per col): [50 70 90]
Sum axis=1 (per row): [ 60 150]
Mean per column:      [25. 35. 45.]
Std per row:          [8.16496581 8.16496581]
Index of max overall: 5
Index of max per col: [1 1 1]


In [ ]:
# ==============================================================================
# LIVE CODE BENCHMARK: COLUMN-WISE NORMALISATION (Z-Score Standardisation)
# Formula: Z = (X - mean) / std
# ==============================================================================
# Matrix: 10,000 rows (samples), 100 columns (features)
N_ROWS, N_COLS = 10_000, 100
dataset = np.random.randn(N_ROWS, N_COLS) * 5 + 20

def python_loop_normalise(mat):
    """Normalises each column using standard nested Python loops."""
    rows, cols = mat.shape
    out = np.empty((rows, cols))
    for j in range(cols):
        # Calculate mean & std for column j
        col_sum = 0.0
        for i in range(rows):
            col_sum += mat[i, j]
        col_mean = col_sum / rows

        variance_sum = 0.0
        for i in range(rows):
            variance_sum += (mat[i, j] - col_mean) ** 2
        col_std = (variance_sum / rows) ** 0.5

        # Normalise column
        for i in range(rows):
            out[i, j] = (mat[i, j] - col_mean) / col_std
    return out

def vectorised_normalise(mat):
    """Normalises all columns simultaneously via axis aggregation & broadcasting."""
    mean = np.mean(mat, axis=0) # shape: (100,)
    std = np.std(mat, axis=0)   # shape: (100,)
    return (mat - mean) / std   # (10000, 100) - (100,) -> broadcasted!

# Validate equivalence
norm_loop = python_loop_normalise(dataset[:100, :10])
norm_vec = vectorised_normalise(dataset[:100, :10])
assert np.allclose(norm_loop, norm_vec)
print("Outputs match perfectly!\n")

print("--- Benchmark: Normalising (10,000 x 100) Matrix ---")
print("1. Nested Python Loops:")
%timeit python_loop_normalise(dataset)

print("2. Vectorised Broadcasting:")
%timeit vectorised_normalise(dataset)

Outputs match perfectly!

--- Benchmark: Normalising (10,000 x 100) Matrix ---
1. Nested Python Loops:
931 ms ± 59.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2. Vectorised Broadcasting:
8.23 ms ± 938 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# ==============================================================================
# SECTION 10: 12 STUDENT EXERCISES
# ==============================================================================

# --- Exercise 1 ---
# Create a 1D array of 20 evenly spaced values between 5 and 50 (inclusive).
# Hint: np.linspace
# YOUR CODE HERE:
ex1 = np.linspace(5, 50, 20)

print(ex1,"\n")

# --- Exercise 2 ---
# Create a 4x4 matrix where border elements are 1 and inside elements are 0.
# YOUR CODE HERE:
ex2 = np.ones((4, 4))
ex2[1:-1, 1:-1] = 0

print(ex2,"\n")

# --- Exercise 3 ---
# Create an array of random integers between 10 and 100 of shape (5, 5).
# Replace all even values with -1 without modifying the original array (return a new array).
# Hint: np.where
# YOUR CODE HERE:
orig = np.random.randint(10, 100, size=(5, 5))
ex3 = np.where(orig % 2 == 0, -1, orig)
print(ex3,"\n")

# --- Exercise 4 ---
# Given a 1D array, extract elements that are greater than 20 AND divisible by 3.
# Hint: bitwise operator &
ex4_arr = np.array([12, 21, 24, 30, 5, 18, 45, 9, 33])
# YOUR CODE HERE:
ex4 = ex4_arr[(ex4_arr > 20) & (ex4_arr % 3 == 0)]
print(ex4,"\n")

# --- Exercise 5 ---
# Given a 2D array, reverse its rows (top row becomes bottom row) using slicing.
ex5_mat = np.arange(16).reshape(4, 4)
# YOUR CODE HERE:
ex5 = ex5_mat[::-1, :]
print(ex5,"\n")

# --- Exercise 6 ---
# Given an array of shape (6, 1) and an array of shape (1, 4), perform an addition
# that outputs an array of shape (6, 4).
# YOUR CODE HERE:
u = np.arange(6).reshape(6, 1)
v = np.arange(4).reshape(1, 4)
ex6 = u + v
print(ex6,"\n")

# --- Exercise 7 ---
# Given a 2D array (5x3), subtract the mean of each column from the respective column.
# YOUR CODE HERE:
mat_ex7 = np.random.rand(5, 3)
ex7 = mat_ex7 - np.mean(mat_ex7, axis=0)
print(ex7,"\n")

# --- Exercise 8 ---
# Given a 2D array (4x5), subtract the mean of each row from the respective row.
# Hint: keepdims=True or expand_dims
# YOUR CODE HERE:
mat_ex8 = np.random.rand(4, 5)
ex8 = mat_ex8 - np.mean(mat_ex8, axis=1, keepdims=True)
print(ex8,"\n")

# --- Exercise 9 ---
# Find the row index of the maximum value in each column of a 2D array.
# YOUR CODE HERE:
mat_ex9 = np.array([[10, 50, 30], [40, 20, 90], [15, 80, 25]])
ex9 = np.argmax(mat_ex9, axis=0)
print(ex9,"\n")

# --- Exercise 10 ---
# Stack two 1D arrays of length 4 as columns into a 2D array of shape (4, 2).
# Hint: np.column_stack or np.vstack with transpose
# YOUR CODE HERE:
c1 = np.array([1, 2, 3, 4])
c2 = np.array([5, 6, 7, 8])
ex10 = np.column_stack((c1, c2))
print(ex10,"\n")

# --- Exercise 11 ---
# Replace all NaN values in a given 1D float array with the mean of non-NaN values.
# Hint: np.isnan(), np.nanmean()
ex11_arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
# YOUR CODE HERE:
mean_val = np.nanmean(ex11_arr)
ex11 = ex11_arr.copy()
ex11[np.isnan(ex11)] = mean_val
print(ex11,"\n")

# --- Exercise 12 ---
# Min-Max Feature Scaling: Normalise a 2D matrix column-wise so all values lie in [0, 1].
# Formula: (X - min) / (max - min)
# YOUR CODE HERE:
X_raw = np.random.randint(1, 100, size=(6, 3)).astype(float)
col_min = np.min(X_raw, axis=0)
col_max = np.max(X_raw, axis=0)
ex12 = (X_raw - col_min) / (col_max - col_min)
print(ex12)

print("All 12 exercises executed successfully!")

[ 5.          7.36842105  9.73684211 12.10526316 14.47368421 16.84210526
 19.21052632 21.57894737 23.94736842 26.31578947 28.68421053 31.05263158
 33.42105263 35.78947368 38.15789474 40.52631579 42.89473684 45.26315789
 47.63157895 50.        ] 

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]] 

[[37 55 -1 -1 -1]
 [-1 55 -1 -1 41]
 [-1 -1 65 -1 75]
 [-1 29 85 79 -1]
 [-1 63 83 39 73]] 

[21 24 30 45 33] 

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]] 

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 

[[-0.09554803 -0.10144041  0.10335442]
 [ 0.13612195  0.27158788 -0.11478917]
 [ 0.41245187 -0.0676702   0.2132808 ]
 [-0.33913432 -0.3462489  -0.10407057]
 [-0.11389147  0.24377162 -0.09777547]] 

[[ 0.05507935 -0.22582882  0.31619781  0.0756644  -0.22111275]
 [ 0.25479592  0.33189532 -0.38422697 -0.12404398 -0.0784203 ]
 [-0.34507194  0.05542049  0.25873589 -0.23422473  0.26514029]
 [ 0.36851312 -0.38738158 -0.05682485  0.14257642 -0.066883

Pandas

In [ ]:
# ==============================================================================
# CELL 0: SETUP & DATASET GENERATION (retail_sales.csv)
# Run this cell first to generate the dataset directly inside Google Colab!
# ==============================================================================
import numpy as np
import pandas as pd

# Create a realistic retail sales dataset
np.random.seed(42)
n_rows = 150

categories = ['Electronics', 'Clothing', 'Home & Kitchen', 'Beauty', 'Books']
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami']
payment_methods = ['Credit Card', 'Debit Card', 'Cash', 'UPI', 'PayPal']
genders = ['Male', 'Female', 'Other']

dates = pd.date_range(start='2024-01-01', end='2024-06-30', periods=n_rows).strftime('%Y-%m-%d')
order_ids = [f"ORD{1000 + i}" for i in range(n_rows)]
customer_ids = [f"CUST{np.random.randint(100, 160)}" for _ in range(n_rows)]
ages = np.random.randint(18, 65, size=n_rows)
gender_col = np.random.choice(genders, size=n_rows, p=[0.48, 0.48, 0.04])
cat_col = np.random.choice(categories, size=n_rows)
qty_col = np.random.randint(1, 6, size=n_rows)
unit_prices = np.random.choice([15.0, 25.5, 49.99, 89.0, 120.0, 299.99, 450.0, 899.0], size=n_rows)
total_amounts = np.round(qty_col * unit_prices, 2)
payments = np.random.choice(payment_methods, size=n_rows)
city_col = np.random.choice(cities, size=n_rows)

raw_df = pd.DataFrame({
    'Order_ID': order_ids,
    'Date': dates,
    'Customer_ID': customer_ids,
    'Gender': gender_col,
    'Age': ages,
    'Category': cat_col,
    'Quantity': qty_col,
    'Unit_Price': unit_prices,
    'Total_Amount': total_amounts,
    'Payment_Method': payments,
    'City': city_col
})

# Inject a few missing values & sentinel strings to demonstrate cleaning
raw_df.loc[10, 'Age'] = np.nan
raw_df.loc[25, 'Payment_Method'] = "MISSING"

raw_df.to_csv("retail_sales.csv", index=False)
print("`retail_sales.csv` successfully created on disk!")

`retail_sales.csv` successfully created on disk!


In [ ]:
# ==============================================================================
# SECTION 1: SERIES VS DATAFRAME & INDEX AS A FIRST-CLASS CITIZEN
# ==============================================================================
# 1. Series: 1D labeled homogeneous array
s = pd.Series([100, 250, 375], index=['store_A', 'store_B', 'store_C'], name="Revenue")
print("--- Pandas Series ---")
print(s)
print(f"Index: {s.index}, Values: {s.values}\n")

# 2. DataFrame: 2D labeled tabular data structure (Collection of aligned Series sharing an Index)
df_toy = pd.DataFrame({
    'Revenue': [100, 250, 375],
    'Expenses': [60, 140, 200]
}, index=['store_A', 'store_B', 'store_C'])

print("--- Pandas DataFrame ---")
print(df_toy)
print(f"Row Index: {df_toy.index.tolist()} | Columns: {df_toy.columns.tolist()}")

# Index Alignment Concept:
# When performing operations between Series, Pandas matches by INDEX LABEL, not position.
bonus = pd.Series([10, 20], index=['store_B', 'store_A'])
print("\nAutomatic Label Alignment (Revenue + Bonus):")
print(df_toy['Revenue'] + bonus) # Notice store_A got 10 and store_B got 20!

--- Pandas Series ---
store_A    100
store_B    250
store_C    375
Name: Revenue, dtype: int64
Index: Index(['store_A', 'store_B', 'store_C'], dtype='object'), Values: [100 250 375]

--- Pandas DataFrame ---
         Revenue  Expenses
store_A      100        60
store_B      250       140
store_C      375       200
Row Index: ['store_A', 'store_B', 'store_C'] | Columns: ['Revenue', 'Expenses']

Automatic Label Alignment (Revenue + Bonus):
store_A    120.0
store_B    260.0
store_C      NaN
dtype: float64


In [ ]:

# ==============================================================================
# SECTION 2: CREATING DATAFRAMES FROM PYTHON & NUMPY STRUCTURES
# ==============================================================================
# 1. From Dictionary of Lists/Arrays
df_from_dict = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Stock': [15, 120, 45]
})

# 2. From List of Dictionaries (Row-oriented)
df_from_records = pd.DataFrame([
    {'Product': 'Monitor', 'Stock': 28},
    {'Product': 'Desk', 'Stock': 10}
])

# 3. From a 2D NumPy Array
np_matrix = np.random.randint(10, 99, size=(3, 3))
df_from_numpy = pd.DataFrame(
    data=np_matrix,
    index=['Row_1', 'Row_2', 'Row_3'],
    columns=['Col_A', 'Col_B', 'Col_C']
)
print("DataFrame from NumPy:\n", df_from_numpy)


In [ ]:
# ==============================================================================
# SECTION 3: READING DATA (read_csv, read_excel, read_json)
# ==============================================================================
# pd.read_csv key parameters:
# - sep: delimiter (default ',')
# - header: row number to use as column names (default 0)
# - names: custom list of column names to override
# - usecols: list of column names or indices to load (saves memory)
# - nrows: number of rows to read from top
# - na_values: additional strings to recognize as NaN/null
# - parse_dates: list of columns to convert to datetime

retail_df = pd.read_csv(
    'retail_sales.csv',
    sep=',',
    usecols=['Order_ID', 'Date', 'Customer_ID', 'Gender', 'Age', 'Category',
             'Quantity', 'Unit_Price', 'Total_Amount', 'Payment_Method', 'City'],
    na_values=['MISSING', 'N/A', 'null'],
    parse_dates=['Date']
)

print(f"Loaded {retail_df.shape[0]} rows and {retail_df.shape[1]} columns.\n")

# Syntax references for other formats:
# df_excel = pd.read_excel('file.xlsx', sheet_name='Sheet1')
# df_json  = pd.read_json('file.json')

In [ ]:
# ==============================================================================
# SECTION 4: FIRST-LOOK PROFILING METHODS (Updated for Pandas 2.0+)
# ==============================================================================
print("1. First 3 rows (.head):")
display(retail_df.head(3))

print("\n2. Dimensions (.shape):", retail_df.shape)
print("3. Data types (.dtypes):\n", retail_df.dtypes)

print("\n4. Structural summary (.info):")
retail_df.info()

print("\n5. Statistical distribution (.describe):")
display(retail_df.describe(include='all'))

print("\n6. Unique counts per column (.nunique):")
print(retail_df.nunique())

print("\n7. Frequency counts for Category (.value_counts):")
print(retail_df['Category'].value_counts(normalize=False))


In [ ]:
# ==============================================================================
# SECTION 5: SELECTION & CONTRAST: .loc vs .iloc
# ==============================================================================
# Setup an explicit string index for clear illustration
sample_df = retail_df.head(5).copy()
sample_df.index = ['idx_a', 'idx_b', 'idx_c', 'idx_d', 'idx_e']
print("Sample DataFrame with Custom Index:\n", sample_df[['Customer_ID', 'Category', 'Total_Amount']])

# --- 1. Column Selection ---
s_col = sample_df['Category']       # Returns a Series (1D)
df_cols = sample_df[['Category']]   # Returns a DataFrame (2D)

# --- 2. .loc (LABEL-BASED) ---
# Syntax: df.loc[row_label_start:row_label_stop, col_name_start:col_name_stop]
# RULE: .loc endpoint IS INCLUSIVE!
loc_result = sample_df.loc['idx_a':'idx_c', ['Category', 'Total_Amount']]
print("\n--- .loc Result ('idx_a' through 'idx_c' inclusive) ---")
print(loc_result)

# --- 3. .iloc (INTEGER POSITION-BASED, 0-indexed) ---
# Syntax: df.iloc[row_idx_start:row_idx_stop, col_idx_start:col_idx_stop]
# RULE: .iloc endpoint IS EXCLUSIVE (standard Python slicing)!
iloc_result = sample_df.iloc[0:2, [5, 8]] # Rows 0 and 1, cols 5 (Category) and 8 (Total_Amount)
print("\n--- .iloc Result (Rows 0:2 exclusive) ---")
print(iloc_result)


In [ ]:
# ==============================================================================
# SECTION 6: CONDITIONAL FILTERING & QUERYING
# ==============================================================================
# Rule: Use & (AND), | (OR), ~ (NOT). ALWAYS wrap individual conditions in parentheses!

# 1. Single condition
cheap_items = retail_df[retail_df['Unit_Price'] < 30]

# 2. Multiple conditions (& / |)
high_val_ny = retail_df[(retail_df['City'] == 'New York') & (retail_df['Total_Amount'] > 500)]
print(f"High-value transactions in New York: {len(high_val_ny)}")

# 3. .isin() - cleaner alternative to chained OR statements
selected_cities = retail_df[retail_df['City'].isin(['Chicago', 'Miami', 'Houston'])]

# 4. .between(low, high) - inclusive range check
young_adults = retail_df[retail_df['Age'].between(18, 25)]

# 5. .query() - SQL-like string syntax (can reference Python variables with @)
target_cat = 'Electronics'
query_result = retail_df.query("Category == @target_cat and Total_Amount >= 1000")
print(f"Electronics orders >= $1000: {len(query_result)}")


In [ ]:
# ==============================================================================
# SECTION 7: ADDING, RENAMING, DROPPING, SORTING, & INDEX MANIPULATION
# ==============================================================================
df_mod = retail_df.copy()

# 1. Adding a new derived column
df_mod['Discounted_Total'] = df_mod['Total_Amount'] * 0.90 # 10% discount

# 2. Renaming columns
df_mod = df_mod.rename(columns={'Total_Amount': 'Gross_Revenue', 'City': 'Location'})

# 3. Dropping columns and rows
df_mod = df_mod.drop(columns=['Customer_ID']) # Drop column
df_mod = df_mod.drop(index=[0, 1])            # Drop first two rows

# 4. Sorting
sorted_df = df_mod.sort_values(by=['Location', 'Gross_Revenue'], ascending=[True, False])

# 5. set_index / reset_index
df_indexed = sorted_df.set_index('Order_ID')
print("Index set to Order_ID:\n", df_indexed.head(2))

df_restored = df_indexed.reset_index() # Restores Order_ID back as a column

In [ ]:

# ==============================================================================
# SECTION 8: LIVE CODE - RETAIL BUSINESS ANALYSIS
# ==============================================================================
print("=== LIVE-CODE DEMO: RETAIL BUSINESS INSIGHTS ===")

# --- Business Question 1 ---
# "Which Electronics transactions exceeded $500 and were paid with a Credit Card?"
q1 = retail_df[
    (retail_df['Category'] == 'Electronics') &
    (retail_df['Total_Amount'] > 500) &
    (retail_df['Payment_Method'] == 'Credit Card')
][['Order_ID', 'Date', 'Customer_ID', 'Total_Amount', 'Payment_Method']]
print("\nQ1: High-Value Electronics (Credit Card):")
display(q1.head())

# --- Business Question 2 ---
# "Find top 5 highest-revenue transactions made by customers aged 25-35 in 'New York' or 'Chicago' buying 'Clothing' or 'Beauty'."
q2 = retail_df[
    (retail_df['Age'].between(25, 35)) &
    (retail_df['City'].isin(['New York', 'Chicago'])) &
    (retail_df['Category'].isin(['Clothing', 'Beauty']))
].sort_values(by='Total_Amount', ascending=False).head(5)
print("\nQ2: Top 5 Targeted Demographic Transactions:")
display(q2[['Order_ID', 'Age', 'City', 'Category', 'Quantity', 'Total_Amount']])

# --- Business Question 3 ---
# "Find all transactions where the Unit_Price is higher than the overall average Unit_Price, sorted by Date descending."
avg_unit_price = retail_df['Unit_Price'].mean()
q3 = retail_df[retail_df['Unit_Price'] > avg_unit_price].sort_values(by='Date', ascending=False)
print(f"\nQ3: Above-Average Unit Price (Avg = ${avg_unit_price:.2f}) - Total records: {len(q3)}:")
display(q3[['Order_ID', 'Date', 'Category', 'Unit_Price', 'Total_Amount']].head())

In [ ]:

# ==============================================================================
# SECTION 9: 5 STUDENT PRACTICE EXERCISES
# ==============================================================================
print("=== STUDENT INDEPENDENT EXERCISES ===")

# --- Exercise 1 ---
# Find all transactions where Quantity is at least 4 and Payment_Method is 'Cash' or 'UPI'.
# YOUR CODE HERE:
ex1 = retail_df[(retail_df['Quantity'] >= 4) & (retail_df['Payment_Method'].isin(['Cash', 'UPI']))]
print(f"Exercise 1 count: {len(ex1)}")


# --- Exercise 2 ---
# Extract only the 'Customer_ID', 'Category', and 'Total_Amount' columns for all transactions in 'Miami' with Total_Amount < 100.
# YOUR CODE HERE:
ex2 = retail_df[(retail_df['City'] == 'Miami') & (retail_df['Total_Amount'] < 100)][['Customer_ID', 'Category', 'Total_Amount']]
print(f"Exercise 2 count: {len(ex2)}")


# --- Exercise 3 ---
# Using .query(), find all female customers ('Female') who purchased items in the 'Books' or 'Home & Kitchen' category.
# YOUR CODE HERE:
ex3 = retail_df.query("Gender == 'Female' and Category in ['Books', 'Home & Kitchen']")
print(f"Exercise 3 count: {len(ex3)}")


# --- Exercise 4 ---
# Identify the top 3 highest Total_Amount orders for senior customers (Age >= 50) and return only Order_ID, Age, Category, and Total_Amount.
# YOUR CODE HERE:
ex4 = (
    retail_df[retail_df['Age'] >= 50]
    .sort_values(by='Total_Amount', ascending=False)
    [['Order_ID', 'Age', 'Category', 'Total_Amount']]
    .head(3)
)
print("\nExercise 4 top 3:")
display(ex4)


# --- Exercise 5 ---
# Filter all rows where Age is NOT missing (NaN) and Total_Amount is between
800 (inclusive).
# Sort the result first by Category (A-Z) and then by Total_Amount (descending).
# YOUR CODE HERE:
ex5 = (
    retail_df[retail_df['Age'].notna() & retail_df['Total_Amount'].between(200, 800)]
    .sort_values(by=['Category', 'Total_Amount'], ascending=[True, False])
)
print(f"\nExercise 5 count: {len(ex5)}")
display(ex5.head())